title: 1º ESO
description: Taller de relaciones digitales responsables
theme: just-the-docs

url: https://estertic2.github.io/porfolio/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Configuración del menú de navegación
just_the_docs:
  # Estructura de navegación
  nav:
    - Home:
        url: /
        children:
          - Bloque 1:
              url: /Bloque1/
          - Tema2:
              url: /tema2/
